// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjX_NZohy3007HsXzwPizVrFXXb_OfB2w',
    appId: '1:54721437520:web:b6feb0e0ee43664d2a1655',
    messagingSenderId: '54721437520',
    projectId: 'master-task-mobile',
    authDomain: 'master-task-mobile.firebaseapp.com',
    storageBucket: 'master-task-mobile.firebasestorage.app',
    measurementId: 'G-MC2PVHHL4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmdJd0ihwIbfSVgpbheEHR6oemiKaeoA',
    appId: '1:54721437520:android:e6f2a68c229457752a1655',
    messagingSenderId: '54721437520',
    projectId: 'master-task-mobile',
    storageBucket: 'master-task-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBap2P7gK1K_C0qJfawJyy3TJYB9dpW6v0',
    appId: '1:54721437520:ios:24b32e648cdad2c62a1655',
    messagingSenderId: '54721437520',
    projectId: 'master-task-mobile',
    storageBucket: 'master-task-mobile.firebasestorage.app',
    androidClientId: '54721437520-1rgd40qvjrn9b4noacpho08lcks2asah.apps.googleusercontent.com',
    iosClientId: '54721437520-e1hjj661tm778dc3adf57droodknmrt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mastertaskMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBap2P7gK1K_C0qJfawJyy3TJYB9dpW6v0',
    appId: '1:54721437520:ios:24b32e648cdad2c62a1655',
    messagingSenderId: '54721437520',
    projectId: 'master-task-mobile',
    storageBucket: 'master-task-mobile.firebasestorage.app',
    iosClientId: '54721437520-e1hjj661tm778dc3adf57droodknmrt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mastertaskMobile',
  );

}